### ISSUE TITLE
JR example, comments on the implementation

### ISSUE THREAD

**Issue by mmider** [mmider/BridgeSDEInference.jl#26]
https://github.com/mmider/BridgeSDEInference.jl/blob/13518e8be46f777462d0ff6b82843712b3b29e31/src/JRNeural.jl#L74-L75 If I understand correctly the model specification from the papers then the above should be a 6x3 matrix with 3x3 zero matrix at the top and 3x3 diagonal matrix at the bottom, instead of a vector of length 6. The same applies to this: https://github.com/mmider/BridgeSDEInference.jl/blob/13518e8be46f777462d0ff6b82843712b3b29e31/src/JRNeural.jl#L151-L152 Then, in here https://github.com/mmider/BridgeSDEInference.jl/blob/13518e8be46f777462d0ff6b82843712b3b29e31/scripts/simulate_JRNeural_to_csv.jl#L27 the first argument specifies the datatype of the Wiener process, which should be 3 dimensional, so it should read ℝ{3}(0.0, 0.0, 0.0).

**Comment by SebaGraz** [comment]
thank you for your comments Marcin! I fixed it now
