### ISSUE TITLE
Discussion after running the Jansen and Rit experiment

### ISSUE THREAD

**Issue by SebaGraz** [mmider/BridgeSDEInference.jl#55]
I have been running the algorithm for the Jansen and Rit model. The results are impressive (see outputs for different time lengths: [1/4 second](https://github.com/mmider/BridgeSDEInference.jl/tree/master/scripts/inference/Jansen_and_Rit/quarter_second/output), [1/2 second](https://github.com/mmider/BridgeSDEInference.jl/tree/master/scripts/inference/Jansen_and_Rit/half_second/output) and [1 second](https://github.com/mmider/BridgeSDEInference.jl/tree/master/scripts/inference/Jansen_and_Rit/second/output))  although it required some manual tuning. Here is a list of things that I would like to understand better (bullet) and I would like to do (todo list):
- If you look at the outputs in all the experiments, the mcmc sometimes gets stuck in local areas, giving a long sequence of rejection (all parameters get stuck), suggesting local maxima in the joint posterior distribution.  This may create problems for the adaptive method since when the sampler get stuck, the transition steps shrinks to 0.   
- For discussions: the kernel needs to be manually tuned depending on the length of observation we use.  
- I want to make sure that \sigma_y of both the real process and the auxiliary process updates when the chain accept a new position for \sigma_y. Is this specified just by [this line](https://github.com/mmider/BridgeSDEInference.jl/blob/a3e4d42ab043f97134a0f9f42cf2dfd07bbc461d/src/examples/Jansen_and_Rit_simple.jl#L155)?  
- [x] I did not understand how to turn off the adaptive scheme for the transition kernel of the mcmc
- [x] I would like to try to give another prior to the parameters (it could fix the first bullet, smoothing the posterior density), can anybody guide me on doing that (I was just thinking at Gaussian priors)?  
Thanks

**Comment by mschauer** [comment]
Would be still nice to have a switch to completely turn of stepsize adaption on a per proposal level.

**Comment by SebaGraz** [comment]
moved on!
