### ISSUE TITLE
Use a signum variable to capture differences in handling of up and down crossings 

### ISSUE THREAD

**Issue by mmider** [mmider/BridgeSDEInference.jl#7]
https://github.com/mmider/FitzHughNagumo.jl/blob/c44fcf9a3fe2ec47148d556a42af960e08f6b1d4/src/mcmc.jl#L117

**Comment by mmider** [comment]
This has been resolved, but the latest merge to master has reverted the nice shortening of code with `s = fpt.upCrossing[cidx] ? 1 : -1`. Introduce it back in the future releases.

**Comment by mschauer** [comment]
Yes, let’s keep track of it here

**Comment by mmider** [comment]
Now, this has been introduced back on the most recent branch `v0.0.2`.

**Comment by mschauer** [comment]
Closed by #25
